global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  # - "first_rules.yml"
  # - "second_rules.yml"

alerting:
  alertmanagers:
    - static_configs:
        - targets:
          # - alertmanager:9093

scrape_configs:
  # Prometheus itself
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  # QuickKub Backend API
  - job_name: 'quickkub-backend'
    static_configs:
      - targets: ['backend:3002']
    metrics_path: '/metrics'
    scrape_interval: 30s
    scrape_timeout: 10s
    honor_labels: true

  # QuickKub Frontend
  - job_name: 'quickkub-frontend'
    static_configs:
      - targets: ['frontend:3000']
    metrics_path: '/api/metrics'
    scrape_interval: 30s
    scrape_timeout: 10s

  # QuickKub Admin Panel
  - job_name: 'quickkub-admin'
    static_configs:
      - targets: ['admin:3001']
    metrics_path: '/metrics'
    scrape_interval: 30s
    scrape_timeout: 10s

  # Nginx
  - job_name: 'nginx'
    static_configs:
      - targets: ['nginx:80']
    metrics_path: '/nginx_status'
    scrape_interval: 30s
    scrape_timeout: 10s

  # PostgreSQL
  - job_name: 'postgres'
    static_configs:
      - targets: ['postgres:5432']
    metrics_path: '/metrics'
    scrape_interval: 30s
    scrape_timeout: 10s

  # Redis
  - job_name: 'redis'
    static_configs:
      - targets: ['redis:6379']
    metrics_path: '/metrics'
    scrape_interval: 30s
    scrape_timeout: 10s

  # MinIO
  - job_name: 'minio'
    static_configs:
      - targets: ['minio:9000']
    metrics_path: '/minio/v2/metrics/cluster'
    scrape_interval: 30s
    scrape_timeout: 10s

  # Node Exporter (if running on host)
  - job_name: 'node-exporter'
    static_configs:
      - targets: ['host.docker.internal:9100']
    scrape_interval: 30s
    scrape_timeout: 10s

  # Docker
  - job_name: 'docker'
    static_configs:
      - targets: ['host.docker.internal:9323']
    scrape_interval: 30s
    scrape_timeout: 10s

  # Health Checks
  - job_name: 'health-checks'
    static_configs:
      - targets: ['backend:3002', 'frontend:3000', 'admin:3001']
    metrics_path: '/health'
    scrape_interval: 60s
    scrape_timeout: 10s
    honor_labels: true

  # Payment Gateway Specific Metrics
  - job_name: 'payment-metrics'
    static_configs:
      - targets: ['backend:3002']
    metrics_path: '/api/metrics/payments'
    scrape_interval: 60s
    scrape_timeout: 10s
    honor_labels: true

  # Transaction Metrics
  - job_name: 'transaction-metrics'
    static_configs:
      - targets: ['backend:3002']
    metrics_path: '/api/metrics/transactions'
    scrape_interval: 60s
    scrape_timeout: 10s
    honor_labels: true

  # Thai Payment Methods Metrics
  - job_name: 'thai-payment-metrics'
    static_configs:
      - targets: ['backend:3002']
    metrics_path: '/api/metrics/thai-payments'
    scrape_interval: 60s
    scrape_timeout: 10s
    honor_labels: true
